poi_geocountry:
    pattern:  /
    defaults: { _controller: "POIWebAppBundle:GeoCountry:index" }

poi_geocountry_show:
    pattern:  /{id}/show
    defaults: { _controller: "POIWebAppBundle:GeoCountry:show" }

poi_geocountry_new:
    pattern:  /new
    defaults: { _controller: "POIWebAppBundle:GeoCountry:new" }

poi_geocountry_create:
    pattern:  /create
    defaults: { _controller: "POIWebAppBundle:GeoCountry:create" }
    requirements: { _method: post }

poi_geocountry_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "POIWebAppBundle:GeoCountry:edit" }

poi_geocountry_update:
    pattern:  /{id}/update
    defaults: { _controller: "POIWebAppBundle:GeoCountry:update" }
    requirements: { _method: post|put }

poi_geocountry_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "POIWebAppBundle:GeoCountry:delete" }
    requirements: { _method: post|delete }
