poi_job:
    pattern:  /
    defaults: { _controller: "POIWebAppBundle:Job:index" }

poi_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "POIWebAppBundle:Job:show" }
    requirements:
        id:  \d+

poi_job_new:
    pattern:  /new
    defaults: { _controller: "POIWebAppBundle:Job:new" }

poi_job_create:
    pattern:  /create
    defaults: { _controller: "POIWebAppBundle:Job:create" }
    requirements: { _method: post }

poi_job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "POIWebAppBundle:Job:edit" }

poi_job_update:
    pattern:  /{token}/update
    defaults: { _controller: "POIWebAppBundle:Job:update" }
    requirements: { _method: post|put }

poi_job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "POIWebAppBundle:Job:delete" }
    requirements: { _method: post|delete }
