Interactive\POIWebAppBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: Interactive\POIWebAppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        description:
            type: text
            nullable: true
        slug:
            type: string
            length: 255
            unique: true
        image:
             type: string
             length: 60
             unique: true
        pinhexcolor:
            type: string
            length: 20
            nullable: true
    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: category
        points_of_interest:
            targetEntity: PointOfInterest
            mappedBy: category
    manyToMany:
        affiliates:
            targetEntity: Affiliate
            mappedBy: categories
    lifecycleCallbacks:
        prePersist: [ setSlugValue ]
        preUpdate: [ setSlugValue ]

