Interactive\POIWebAppBundle\Entity\GeoCity:
    type: entity
    table: geo_cities
    indexes:
        geo_states_id_state_idx:
            columns:
                - id_state
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    manyToOne:
        idState:
            targetEntity: GeoState
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_state:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
