Interactive\POIWebAppBundle\Entity\GeoCity:
    type: entity
    table: geo_cities
    indexes:
        geo_states_id_state_idx:
            columns:
                - id_state
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    manyToOne:
        geostate:
            targetEntity: GeoState
            inversedBy: geo_cities
            joinColumns:
                id_state:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
