Interactive\POIWebAppBundle\Entity\GeoState:
    type: entity
    table: geo_states
    indexes:
        fk_geo_estados_geo_paises1:
            columns:
                - id_country
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    manyToOne:
        idCountry:
            targetEntity: GeoCountry
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_country:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
