Interactive\POIWebAppBundle\Entity\PointOfInterest:
    type: entity
    table: point_of_interest
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        latitude:
            type: string
            length: 255
        longitude:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        address:
            type: string
            legth: 255
            nullable: true
        is_activated:
            type: boolean
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: point_of_interest
            joinColumn:
                name: category_id
                referencedColumnName: id
        geocity:
            targetEntity: GeoCity
            inversedBy: point_of_interest
            joinColumn:
                name: geocity_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setExpiresAtValue ]
        preUpdate: [setUpdatedAtValue ]