Interactive\POIWebAppBundle\Entity\PointOfInterest:
    type: entity
    table: point_of_interest
    repositoryClass: Interactive\POIWebAppBundle\Repository\PointOfInterestRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 250
            nullable: false
        phone:
            type: string
            length: 60
            nullable: true
        phone_ext:
            type: string
            length: 30
            nullable: true
        fax:
            type: string
            length: 60
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        schedule:
            type: string
            length: 255
            nullable: true
        latitude:
            type: string
            length: 255
            nullable: false
        longitude:
            type: string
            length: 255
            nullable: false
        description:
            type: text
            nullable: true
        address:
            type: string
            legth: 255
            nullable: false
        is_activated:
            type: boolean
            nullable: true
            default: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: point_of_interest
            nullable: false
            joinColumn:
                name: category_id
                referencedColumnName: id
        geocity:
            targetEntity: GeoCity
            inversedBy: point_of_interest
            nullable: false
            joinColumn:
                name: geocity_id
                referencedColumnName: id
        route:
            targetEntity: Route
            inversedBy: point_of_interest
            nullable: true
            joinColumn:
                name: route_id
                referencedColumnName: id
        near_route_point:
            targetEntity: RoutePoint
            inversedBy: point_of_interest
            nullable: true
            joinColumn:
                name: near_route_point_id
                referencedColumnName: id        
             
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue,setIsActivatedVale]
        preUpdate: [setUpdatedAtValue ]