Interactive\POIWebAppBundle\Entity\Role:
    type: entity
    table: role
    repositoryClass: Interactive\POIWebAppBundle\Repository\RoleRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        role:
            type: string
            length: 255
    manyToMany:
        users:
            targetEntity: User
            joinTable:
                name: user_role
                joinColumns:
                    role_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id