Interactive\POIWebAppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
            nullable: true
        password:
            type: string
            length: 255
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        email:
            type: string
            length: 255
            nullable: false;
            unique: false;
    manyToMany:
        roles:
            targetEntity: Role
            mappedBy: users
 