security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #login:
         #   pattern:  ^/demo/secured/login$
          #  security: false

        #secured_area:
         #   pattern:    ^/demo/secured/
          #  form_login:
           #     check_path: _security_check
           #     login_path: _demo_login
            #logout:
             #   path:   _demo_logout
              #  target: _demo
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: interactive_poiwebapp_homepage
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }
        
    providers:
        #in_memory:
         #   memory:
         #       users:
         #           admin: { password: adminpass, roles: 'ROLE_ADMIN' }
         main:
            entity: { class: Interactive\POIWebAppBundle\Entity\User, property: username }
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        Interactive\POIWebAppBundle\Entity\User: sha512
