poi_web_app_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: POIWebAppBundle:Default:index }
    
POIWebAppBundle_poi_job:
        resource: "@POIWebAppBundle/Resources/config/routing/job.yml"
        prefix:   /poi_job
