POIWebAppBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: POIWebAppBundle:Category:show, page: 1 }

POIWebAppBundle_homepage:
    pattern:  /
    defaults: { _controller: POIWebAppBundle:Job:index }

poi_web_app_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: POIWebAppBundle:Default:index }
    
POIWebAppBundle_poi_job:
        resource: "@POIWebAppBundle/Resources/config/routing/job.yml"
        prefix:   /poi_job
