poi_web_app_poi_route_point:
    resource: "@POIWebAppBundle/Resources/config/routing/routepoint.yml"
    prefix:   /poi_route_point

poi_web_app_poi_route:
    resource: "@POIWebAppBundle/Resources/config/routing/route.yml"
    prefix:   /poi_route

#All routes insed are secured      
POIWebAppBundle_poi_user:
        resource: "@POIWebAppBundle/Resources/config/routing/user.yml"
        prefix:   /admin
        
POIWebAppBundle_poi_geocity:
        resource: "@POIWebAppBundle/Resources/config/routing/geocity.yml"
        prefix:   /geocity
#All routes insed are secured
POIWebAppBundle_poi_category:
        resource: "@POIWebAppBundle/Resources/config/routing/category.yml"
        prefix:   /admin
#There are login-secured routes and there are unsecured routes
POIWebAppBundle_poi_point:
        resource: "@POIWebAppBundle/Resources/config/routing/pointofinterest.yml"
        prefix:   /

POIWebAppBundle_poi_route:
        resource: "@POIWebAppBundle/Resources/config/routing/route.yml"
        prefix:   /poi_route
        
POIWebAppBundle_poi_route_point:
        resource: "@POIWebAppBundle/Resources/config/routing/routepoint.yml"
        prefix:   /poi_route_point
  
login:
    pattern:   /login
    defaults:  { _controller: POIWebAppBundle:Default:login }
    
login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
    defaults: { _controller: "POIWebAppBundle:User:dashboard" }