POIWebAppBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: POIWebAppBundle:Category:showJobs, page: 1 }

POIWebAppBundle_homepage:
    pattern:  /
    defaults: { _controller: POIWebAppBundle:Job:index }

poi_web_app_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: POIWebAppBundle:Default:index }
    
POIWebAppBundle_poi_job:
        resource: "@POIWebAppBundle/Resources/config/routing/job.yml"
        prefix:   /poi_job
        
POIWebAppBundle_poi_point:
        resource: "@POIWebAppBundle/Resources/config/routing/pointofinterest.yml"
        prefix:   /admin
        
POIWebAppBundle_poi_user:
        resource: "@POIWebAppBundle/Resources/config/routing/user.yml"
        prefix:   /admin

POIWebAppBundle_poi_category:
        resource: "@POIWebAppBundle/Resources/config/routing/category.yml"
        prefix:   /admin 
       
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin_sonata
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin_sonata
  
login:
    pattern:   /login
    defaults:  { _controller: POIWebAppBundle:Default:login }
    
login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout