services:
    interactive.poiwebapp.admin.category:
        class: Interactive\POIWebAppBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments:
            - ~
            - Interactive\POIWebAppBundle\Entity\Category
            - 'POIWebAppBundle:CategoryAdmin'
 
    interactive.poiwebapp.admin.job:
        class: Interactive\POIWebAppBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments:
            - ~
            - Interactive\POIWebAppBundle\Entity\Job
            - 'POIWebAppBundle:JobAdmin'
            
    interactive.poiwebapp.admin.user_manager:
        class: Interactive\POIWebAppBundle\DependencyInjection\UserManager
        arguments:
            - @security.encoder_factory