<?php
namespace Interactive\POIWebAppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PointOfInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointOfInterestRepository extends EntityRepository
{
    
    public function getPointsOfInterest($max = null, $offset = null)
    {
        $qb = $this->createQueryBuilder('j')
            ->orderBy('j.geocity', 'DESC');
 
        if($max) {
            $qb->setMaxResults($max);
        }
 
        if($offset) {
            $qb->setFirstResult($offset);
        }
 
        $query = $qb->getQuery();
 
        return $query->getResult();
    }
    
    public function countPointsOfInterest()
    {
        $qb = $this->createQueryBuilder('j')
            ->select('count(j.id)');
        $query = $qb->getQuery();
        return $query->getSingleScalarResult();
    }
}